import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          blue: "#0057FF",
          purple: "#7B2FFF",
          cyan: "#00D4FF",
        },
        dark: {
          900: "#06080F",
          800: "#0A0D16",
          700: "#0D1117",
          600: "#111827",
          500: "#1A2235",
          border: "#1E2A3A",
          border2: "#263040",
        },
        text: {
          white: "#F0F6FF",
          muted: "#6B7A99",
          dim: "#4A5568",
        },
        "on-secondary-fixed": "#171c20",
        "secondary-fixed": "#dfe3e8",
        "primary-fixed": "#d9e2ff",
        "on-primary-fixed": "#001946",
        "surface-dim": "#dbdadb",
        "surface-container-highest": "#e3e2e3",
        "inverse-surface": "#303031",
        "background": "#faf9fa",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#42474b",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e2e3",
        "surface-container": "#efedee",
        "on-primary-container": "#e7ebff",
        "outline": "#737784",
        "surface-tint": "#2259bf",
        "on-error": "#ffffff",
        "tertiary-container": "#bfab49",
        "primary": "#094cb2",
        "on-tertiary-fixed-variant": "#524600",
        "tertiary-fixed": "#f9e37a",
        "surface-bright": "#faf9fa",
        "on-background": "#1b1c1d",
        "secondary-fixed-dim": "#c2c7cc",
        "on-secondary-container": "#606569",
        "tertiary-fixed-dim": "#dcc661",
        "surface-container-low": "#f5f3f4",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f2f0f1",
        "primary-fixed-dim": "#b1c5ff",
        "on-tertiary-fixed": "#211b00",
        "tertiary": "#6d5e00",
        "inverse-primary": "#b1c5ff",
        "on-surface": "#1b1c1d",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8e9",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#3366cc",
        "secondary-container": "#dfe3e8",
        "on-primary-fixed-variant": "#00419d",
        "error": "#ba1a1a",
        "outline-variant": "#c3c6d5",
        "on-surface-variant": "#434653",
        "secondary": "#5a5f63",
        "on-tertiary-container": "#4a3f00",
        "surface": "#faf9fa"
      },
      backgroundImage: {
        'gradient-main': 'linear-gradient(135deg, #0057FF, #7B2FFF)',
        'gradient-cyan': 'linear-gradient(135deg, #00D4FF, #0057FF)',
        'gradient-warm': 'linear-gradient(135deg, #FF6B35, #F7C948)',
      },
      fontFamily: {
        sans: ['var(--font-inter)'],
        heading: ['var(--font-jakarta)'],
        mono: ['var(--font-grotesk)'],
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Public Sans", "sans-serif"]
      },
    },
  },
  plugins: [],
};

export default config;
